#!/usr/bin/env python3
"""Fail the run when Apple metadata artifacts are staged for commit."""

from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

APPLE_WARNING = dedent(
    """
    Found macOS metadata artifacts staged for commit. These files are generated by Finder
    or the HFS+ filesystem and should never be checked into source control.

    To clean your working tree run:
      scripts/cleanup-macos-cruft.sh
    """
).strip()


def main(argv: list[str]) -> int:
    offenders = sorted({Path(arg) for arg in argv})
    if not offenders:
        return 0

    sys.stderr.write("Apple metadata artifacts detected:\n")
    for path in offenders:
        sys.stderr.write(f"  - {path}\n")

    sys.stderr.write("\n" + APPLE_WARNING + "\n")
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
