name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
      - pyproject.toml
      - uv.lock
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml
      - pyproject.toml
      - uv.lock

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      CHIRON_DISABLE_VENDOR_WHEELHOUSE: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv toolchain
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Sync project dependencies
        run: uv sync --all-extras --dev
        env:
          UV_PYTHON: "3.12"

      - name: Run Copilot readiness tests
        run: uv run -- python -m pytest \
          tests/test_sitecustomize.py \
          tests/test_github_copilot_module.py \
          tests/test_cli_github_copilot.py \
          --no-cov
